name: Integrity

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:

    - name: Checkout Respository
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4

    - name: Setup NodeJS with PNPM Caching
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        registry-url: 'https://registry.npmjs.org'
        scope: '@do-ob'
        cache: 'pnpm'

    - name: Install NodeJS Dependencies
      run: pnpm install --frozen-lockfile

    - name: Test Projects
      run: pnpm lint

    - name: Test Projects
      run: pnpm test
