name: Publish

on:
  workflow_call:
    inputs:
      access:
        type: string
        description: 'Publish Access'
        default: 'public'
        required: false
      tag:
        type: string
        description: 'Publish Tag'
        default: 'latest'
        required: false
      scope:
        type: string
        description: 'Publish Scope'
        default: '@do-ob'
        required: false
    

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: Build and Publish

    steps:

    - name: Checkout Respository
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4

    - name: Setup NodeJS with PNPM Caching
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        registry-url: 'https://registry.npmjs.org'
        scope: ${{ github.event.inputs.scope }}
        cache: 'pnpm'

    - name: Install NodeJS Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Projects
      run: pnpm build

    - name: Publish Project (Dispatched)
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: pnpm publish -r --tag ${{ github.event.inputs.tag }} --access ${{ github.event.inputs.access }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish Project (Called)
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: pnpm publish -r --tag ${{ inputs.tag }} --access ${{ inputs.access }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}