name: Release Please

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: 'The target branch for the release.'
        default: 'main'
        required: false

jobs:
  integrity:
    uses: do-ob-io/shared/.github/workflows/integrity.yml@main
    secrets: inherit
  
  release-please:
    needs: integrity
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
    - uses: googleapis/release-please-action@v4
      id: release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target-branch: ${{ github.event.inputs.branch }}
        config-file: release-please-config.json
        manifest-file: release-please-manifest.json

  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' || needs.release-please.outputs.releases_created == true }}
    uses: do-ob-io/shared/.github/workflows/publish.yml@main
    secrets: inherit
